=== m-ringler/hspiel/radiosendeplaetze.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  encoding: UTF-8
  Namespaces
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.mospace.de/hspiel" xmlns:hspiel="http://www.mospace.de/hspiel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
  <!-- Das Wurzel-Element -->
  <xs:element name="senderliste">
    <xs:annotation>
      <xs:documentation>Senderliste ist das Wurzelelement der Sendeplatz-Übersicht. Es enthält
Senderfamilien als Tochterelemente.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="hspiel:senderfamilie"/>
      </xs:sequence>
      <xs:attributeGroup ref="hspiel:senderliste.attlist"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="senderliste.attlist">
    <xs:attribute ref="xsi:schemaLocation" use="required"/>
  </xs:attributeGroup>
  <xs:element name="senderfamilie">
    <xs:annotation>
      <xs:documentation>Senderfamilie/Rundfunkanstalt.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="hspiel:sender"/>
      </xs:sequence>
      <xs:attributeGroup ref="hspiel:senderfamilie.attlist"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="senderfamilie.attlist">
    <xs:attributeGroup ref="hspiel:id.att"/>
    <xs:attributeGroup ref="hspiel:name.att"/>
    <xs:attributeGroup ref="hspiel:url.att"/>
    <xs:attribute name="frequenzenurl" type="xs:anyURI"/>
  </xs:attributeGroup>
  <xs:element name="sender">
    <xs:annotation>
      <xs:documentation>Ein einzelner Sender mit einer oder mehreren eigenen Frequenzen und/oder
Livestreams, auf denen das gleiche Programm gesendet wird.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="hspiel:sender.content">
          <xs:attributeGroup ref="hspiel:sender.attlist"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="sender.attlist">
    <xs:attributeGroup ref="hspiel:id.att"/>
    <xs:attributeGroup ref="hspiel:name.att"/>
    <xs:attributeGroup ref="hspiel:url.att"/>
    <xs:attributeGroup ref="hspiel:programmurl.att"/>
    <xs:attribute name="longname" use="required" type="xs:string"/>
    <xs:attribute name="frequenzenurl" type="xs:anyURI"/>
    <xs:attribute name="sendeschema" type="xs:anyURI"/>
  </xs:attributeGroup>
  <xs:complexType name="sender.content">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="hspiel:livestream"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="hspiel:sendung"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="livestream" type="hspiel:livestream.content">
    <xs:annotation>
      <xs:documentation>Ein Webradio-Angebot.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="livestream.content">
    <xs:sequence>
      <xs:element ref="hspiel:url"/>
      <xs:element ref="hspiel:typ"/>
      <xs:element ref="hspiel:mplayertyp"/>
      <xs:element minOccurs="0" ref="hspiel:psradioid"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="sendung">
    <xs:annotation>
      <xs:documentation>Eine Radiosendung mit unter Umständen mehreren Sendeterminen.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="hspiel:sendung.content">
          <xs:attributeGroup ref="hspiel:sendung.attlist"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="sendung.attlist">
    <xs:attributeGroup ref="hspiel:id.att"/>
    <xs:attributeGroup ref="hspiel:name.att"/>
    <xs:attribute name="programmurl" type="xs:anyURI"/>
  </xs:attributeGroup>
  <xs:complexType name="sendung.content">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" ref="hspiel:kategorie"/>
      <xs:element maxOccurs="unbounded" ref="hspiel:sendetermin"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="kategorie" type="hspiel:kategorie.datatype">
    <xs:annotation>
      <xs:documentation>Eine Sendungskategorie.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="sendetermin">
    <xs:annotation>
      <xs:documentation>Ein einzelner Sendetermin. Das Attribut "name" sollte für "sendetermin"
nur benutzt werden, wenn es sich um die identische Wiederholung einer
anderen Ausstrahlung handelt. Andernfalls soll ein eigenes Element "sendung"
verwendet werden.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attributeGroup ref="hspiel:sendetermin.attlist"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="sendetermin.attlist">
    <xs:attribute name="id" type="xs:ID"/>
    <xs:attribute name="tag" use="required" type="hspiel:DAY.datatype"/>
    <xs:attribute name="zeit" use="required" type="hspiel:zeit.datatype"/>
    <xs:attribute name="dauer" type="hspiel:dauer.datatype"/>
    <xs:attribute name="intervall" type="xs:string"/>
    <xs:attribute name="wdhvon" type="xs:IDREF"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="anmerkung" type="xs:string"/>
  </xs:attributeGroup>
  <xs:element name="url" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>Eine Internet-Adresse.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="psradioid" type="xs:nonNegativeInteger">
    <xs:annotation>
      <xs:documentation>Die Phonostar channelid des Senders bzw. Livestreams.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="typ" type="hspiel:livestreamtyp.datatype">
    <xs:annotation>
      <xs:documentation>Der Anzeigename für das Datenformat des Livestreams.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="mplayertyp" type="hspiel:mplayertyp.datatype">
    <xs:annotation>
      <xs:documentation>Das genaue Datenformat des Livestreams, zur maschinellen Weiterverarbeitung.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <!-- Universal-Attribute -->
  <xs:attributeGroup name="url.att">
    <xs:attribute name="url" use="required" type="xs:anyURI"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="programmurl.att">
    <xs:attribute name="programmurl" use="required" type="xs:anyURI"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="frequrl.att">
    <xs:attribute name="frequenzenurl" use="required" type="xs:anyURI"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="id.att">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="name.att">
    <xs:attribute name="name" use="required" type="xs:string"/>
  </xs:attributeGroup>
  <!-- Datentypen -->
  <xs:simpleType name="mplayertyp.datatype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ra"/>
      <xs:enumeration value="rm"/>
      <xs:enumeration value="m3u"/>
      <xs:enumeration value="asx"/>
      <xs:enumeration value="wma"/>
      <xs:enumeration value="mp3"/>
      <xs:enumeration value="smil"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="livestreamtyp.datatype">
    <xs:annotation>
      <xs:documentation>Der Typ des Webradioangebots. Für Webradioangebote im MP3-Format soll
"MP3" verwendet werden, ebenso für Angebote im Ogg-Vorbis-Format "OGG".
"RP" steht als Sammelbezeichnung für die proprietären RealPlayer-Formate,
"WM" ebenso für proprietäre Windows-Media-Formate.
Livestreams in nicht-proprietären Formaten sollten bevorzugt angegeben
werden. Dabei soll dem MP3-Format
der Vorzug gegeben werden, da zur Zeit das Ogg-Vorbis-Format noch keine
vergleichbare Soft- und Hardware-Unterstützung genießt,</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="RP"/>
      <xs:enumeration value="WM"/>
      <xs:enumeration value="MP3"/>
      <xs:enumeration value="OGG"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="kategorie.datatype">
    <xs:annotation>
      <xs:documentation>Eine Sendungskategorie. Hörspiele erhalten in der Regel die Kategorie
"Hörspiel allgemein", es sei denn es handelt sich um Sendungen speziell
für Kinder ("Kinder"), um Krimis ("Krimi") oder um Klangkunst und Hörspiele
eher avantgardistischer Natur ("Experimentelles Hörspiel"). Falls an einem
bestimmten Sendetermin stets nur Teile mehrteiliger Hörspiele gesendet
werden, soll die Kategorie "Serie" verwendet werden. "Literatur" soll
ausschließlich für Lesungen nicht-szenischer Werke verwendet werden,
"Theater" für Tonaufnahmen tatsächlicher Theateraufführungen.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Kinder"/>
      <xs:enumeration value="Literatur"/>
      <xs:enumeration value="Feature"/>
      <xs:enumeration value="Serie"/>
      <xs:enumeration value="Krimi"/>
      <xs:enumeration value="Dialekt"/>
      <xs:enumeration value="Hörspiel allgemein"/>
      <xs:enumeration value="Experimentelles Hörspiel"/>
      <xs:enumeration value="Theater"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="dauer.datatype">
    <xs:annotation>
      <xs:documentation>Dauer in ganzen Minuten. Ein angehängtes Plus-Zeichen kann verwendet werden,
um auszudrücken, dass die Dauer den angegebenen Wert gelegentlich
überschreiten kann. Variiert die Dauer stark, so soll das Attribut "dauer"
überhaupt nicht angegeben werden.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="\d+\+?"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="zeit.datatype">
    <xs:annotation>
      <xs:documentation>Eine minutengenaue 24h-Uhrzeit in MEZ/MESZ;
mit zweistelligen Stunden zwischen 00 und 23
und zweistelligen Minuten zwischen 00 und 59</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="(([0-1][0-9])|(2[0-3])):[0-5][0-9]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DAY.datatype">
    <xs:annotation>
      <xs:documentation>Wochentag als Ganzzahl zwischen 0 und 7.
0 und 7 stehen für Sonntag. 1 = Montag, 2 = Dienstag, etc.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="7"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== m-ringler/hspiel/hspiel.xml
<?xml version="1.0" encoding="utf-8"?>
<senderliste
    xmlns="http://www.mospace.de/hspiel"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mospace.de/hspiel/ radiosendeplaetze.xsd">


  <!-- SR -->
    <senderfamilie
        id="sr"
        name="Saarländischer Rundfunk"
        url="http://www.sr-online.de/">
            <!-- SR1 -->
        <sender
            id="sr1"
            name="SR 1 Europawelle"
            longname="Saarländischer Rundfunk Europawelle"
            url="http://www.sr-online.de/sronline/sr1/uebersicht/index.html"
            programmurl="http://www.sr-online.de/sronline/sr1/programm/index.html"
            frequenzenurl="http://www.sr-online.de/sronline/sr1/programm/frequenzen/index.html">
            <livestream>
                <url>http://streaming01.sr-online.de/sr1_2.m3u</url>
                <typ>MP3</typ>
                <mplayertyp>m3u</mplayertyp>
                <psradioid>153</psradioid>
            </livestream>
       <!-- Radiotatort -->
            <sendung
                id="sr1_radiotatort"
                name="Radiotatort"
                programmurl="http://www.ard.de/home/radio/ARD_Radio_Tatort/94130/index.html">
                <kategorie>Krimi</kategorie>
                <sendetermin
                    tag="1"
                    zeit="20:00"
                    dauer="60"
                    intervall="1x im Monat"
                    wdhvon="nwradio_radiotatort_mi"/>
            </sendung>
        </sender>
        <!-- SR2 -->
        <sender
            id="sr2"
            name="SR 2 KulturRadio"
            longname="Saarländischer Rundfunk KulturRadio"
            url="http://www.sr-online.de/sronline/sr2/uebersicht/index.html"
            programmurl="http://www.sr-online.de/sronline/sr2/programmvorschau/index.html"
            frequenzenurl="http://www.sr-online.de/sronline/sr2/service/frequenzen/index.html">
            <livestream>
                <url>http://streaming01.sr-online.de/sr2_2.m3u</url>
                <typ>MP3</typ>
                <mplayertyp>m3u</mplayertyp>
                <psradioid>154</psradioid>
            </livestream>
      <!-- SR2 FeatureZeit -->
            <sendung
                id="sr2_featurezt"
                name="FeatureZeit"
                programmurl="http://www.sr-online.de/sronline/sr2/sendungen_a-z/featurezeit/index.html">
                <kategorie>Feature</kategorie>
                <sendetermin
                    tag="6"
                    zeit="09:05"
                    dauer="55"/>
            </sendung>
      <!-- SR2 HörspielZeit -->
            <sendung
                id="sr2_hspielzt"
                name="Hörspielzeit"
                programmurl="http://www.sr-online.de/sronline/sr2/sendungen_a-z/hoerspielzeit/index.html">
                <kategorie>Hörspiel allgemein</kategorie>
                <kategorie>Krimi</kategorie>
                <!-- <sendetermin tag="4" zeit="20:04" dauer="56" anmerkung="wenn nicht um 18:00"/> -->
                <!--<sendetermin tag="4" zeit="20:04" dauer="56" anmerkung="am 19.11. sonst um 18:00"/>-->
                <sendetermin
                    tag="7"
                    anmerkung="darin einmal im Monat Radiotatort"
                    zeit="17:04"/>
            </sendung>
      <!-- SR2 Fortsetzung folgt -->
            <sendung
                id="sr2_forts"
                name="Fortsetzung folgt..."
                programmurl="http://www.sr-online.de/sronline/sr2/sendungen_a-z/fortsetzung_folgt/index.html">
                <kategorie>Serie</kategorie>
                <sendetermin
                    tag="1"
                    zeit="14:05"
                    dauer="25"/>
                <sendetermin
                    tag="2"
                    zeit="14:05"
                    dauer="25"/>
                <sendetermin
                    tag="3"
                    zeit="14:05"
                    dauer="25"/>
                <sendetermin
                    tag="4"
                    zeit="14:05"
                    dauer="25"/>
                <sendetermin
                    tag="5"
                    zeit="14:05"
                    dauer="25"/>
            </sendung>
        </sender>
    </senderfamilie>

  <!-- Radio Bremen -->
    <!-- aktualisiert 2009-03-30 -->
    <senderfamilie
        id="rb"
        name="Radio Bremen"
        url="http://www.radiobremen.de/">
    <!-- Nordwestradio -->
        <sender
            id="nwradio"
            name="nordwest radio"
            longname="Radio Bremen nordwest radio"
            url="http://www.radiobremen.de/nordwestradio/"
            frequenzenurl="http://www.radiobremen.de/nordwestradio/info/frequenzen/"
            programmurl="http://www.radiobremen.de/nordwestradio/sendungen/hoerspiel/">
            <livestream>
                <url>http://dl-ondemand.radiobremen.de/nordwestradio.m3u</url>
                <typ>MP3</typ>
                <mplayertyp>m3u</mplayertyp>
                <psradioid>5556</psradioid>
            </livestream>
       <!-- Radiotatort -->
            <sendung
                id="nwradio_radiotatort"
                name="Radiotatort"
                programmurl="http://www.ard.de/home/radio/ARD_Radio_Tatort/94130/index.html">
                <kategorie>Krimi</kategorie>
                <sendetermin
                    tag="3"
                    zeit="19:05"
                    dauer="55"
                    intervall="1x im Monat"
                    id="nwradio_radiotatort_mi"/>
            </sendung>
       <!-- Hörspiel -->
            <sendung
                id="nwradio_hspiel"
                name="Hörspiel">
                <kategorie>Hörspiel allgemein</kategorie>
                <sendetermin
                    tag="5"
                    zeit="19:05"
                    dauer="55"
                    intervall="14-täglich"/>
            </sendung>
      <!-- Niederdeutsches Hörspiel -->
            <sendung
                id="nwradio_ndthspiel"
                name="Niederdeutsches Hörspiel"
                programmurl="http://www.radiobremen.de/nordwestradio/sendungen/niederdeutsches_hoerspiel/">
                <kategorie>Dialekt</kategorie>
                <sendetermin
                    tag="7"
                    zeit="17:05"
                    dauer="55"
                    intervall="14-täglich"
                    id="nwradio_ndthspiel_so"/>
                <sendetermin
                    tag="1"
                    zeit="21:05"
                    dauer="55"
                    intervall="14-täglich"
                    id="nwradio_ndthspiel_mo"
                    wdhvon="nwradio_ndthspiel_so"/>
            </sendung>
      <!-- Feature -->
            <sendung
                id="nwradio_feature"
                name="Feature"
                programmurl="http://www.radiobremen.de/nordwestradio/sendungen/feature/">
                <kategorie>Feature</kategorie>
                <sendetermin
                    tag="7"
                    zeit="09:05"
                    dauer="55"
                    intervall="14-täglich"
                    id="nwradio_feature_so"/>
                <sendetermin
                    tag="3"
                    zeit="19:05"
                    dauer="55"
                    intervall="14-täglich"
                    id="nwradio_feature_mi"
                    wdhvon="nwradio_feature_so"/>
            </sendung>
      <!-- Fundsachen -->
            <sendung
                id="nwradio_fundsachen"
                name="Fundsachen"
                programmurl="http://www.radiobremen.de/nordwestradio/sendungen/feature/">
                <kategorie>Literatur</kategorie>
                <sendetermin
                    tag="7"
                    zeit="09:05"
                    dauer="55"
                    intervall="14-täglich"
                    id="nwradio_fundsachen_so"/>
            </sendung>
      <!-- Lesebuch -->
            <sendung
                id="nwradio_lesebuch"
                name="Lesebuch"
                programmurl="http://www.radiobremen.de/nordwestradio/sendungen/lesebuch/">
                <kategorie>Literatur</kategorie>
                <sendetermin
                    tag="1"
                    zeit="18:30"
                    dauer="30"/>
                <sendetermin
                    tag="2"
                    zeit="18:30"
                    dauer="30"/>
                <sendetermin
                    tag="3"
                    zeit="18:30"
                    dauer="30"/>
                <sendetermin
                    tag="4"
                    zeit="18:30"
                    dauer="30"/>
                <sendetermin
                    tag="5"
                    zeit="18:30"
                    dauer="30"/>
            </sendung>
        </sender>
        <!-- Bremen Vier -->
        <sender
            id="rb4"
            name="Bremen 4"
            longname="Radio Bremen Vier"
            url="http://www.radiobremen.de/bremenvier/"
            frequenzenurl="http://www.radiobremen.de/bremenvier/ueber-uns/kontakt/"
            programmurl="http://www.radiobremen.de/bremenvier/programm/themen/hoerbuecher/">
            <livestream>
                <url>http://dl-ondemand.radiobremen.de/bremenvier.m3u</url>
                <typ>MP3</typ>
                <mplayertyp>m3u</mplayertyp>
                <psradioid>7004</psradioid>
            </livestream>
       <!-- Radiotatort -->
            <sendung
                id="rb4_radiotatort"
                name="Radiotatort"
                programmurl="http://www.ard.de/home/radio/ARD_Radio_Tatort/94130/index.html">
                <kategorie>Krimi</kategorie>
                <sendetermin
                    tag="3"
                    zeit="19:05"
                    dauer="55"
                    intervall="1x im Monat"
